# Nom de l'application
app = "cleanback"

# Configuration de build (Dockerfile ou Buildpacks)
[build]
  # Si vous utilisez un Dockerfile, il est nécessaire de préciser le chemin du Dockerfile
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[deploy]
  restart = "always"

[[vm]]
  memory = "1gb"
  cpus = 1
